# Generated by Django 4.0.5 on 2022-06-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submission_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='hash',
        ),
        migrations.AlterField(
            model_name='submission',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
