# Generated by Django 4.0.5 on 2022-06-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_submission_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
    ]
