# Generated by Django 4.0.5 on 2022-06-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_question_survey_alter_submission_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='submission',
            name='answer',
            field=models.CharField(max_length=25000),
        ),
    ]
