# Generated by Django 4.0.5 on 2022-06-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_submission_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('integer', 'integer')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
