# Generated by Django 4.0.5 on 2022-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_submission_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
