# Generated by Django 4.0.5 on 2022-06-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
