# Generated by Django 4.0.5 on 2022-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_submission_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
