# Generated by Django 4.0.5 on 2022-06-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_submission_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='test',
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
    ]
