# Generated by Django 4.0.5 on 2022-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_submission_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('textfield', 'textfield'), ('integerfield', 'integer')], default='textfield', max_length=200),
        ),
    ]
