# Generated by Django 4.0.5 on 2022-06-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('textfield', 'textfield'), ('integerfield', 'integerfield')], default='textfield', max_length=200),
        ),
    ]
