# Generated by Django 4.0.5 on 2022-06-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_submission_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('charfield', 'charfield'), ('integerfield', 'integerfield')], default='charfield', max_length=200),
        ),
    ]
