# Generated by Django 4.0.5 on 2022-06-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_survey_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='test',
        ),
    ]
