# Generated by Django 4.0.5 on 2022-06-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_submission_bash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='bash',
        ),
    ]
