# Generated by Django 4.0.5 on 2022-06-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_question_survey_alter_submission_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='bash',
            field=models.CharField(default='defaulthash', max_length=10),
        ),
    ]
