# Generated by Django 4.0.5 on 2022-06-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_submission_bash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='bash',
        ),
        migrations.AddField(
            model_name='submission',
            name='hash',
            field=models.CharField(default='def1234567', max_length=10),
        ),
    ]
